name: subtree-test integration

on:
  push:
    branches: [ master ]

jobs:
  push-subtree-test-changes:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Push to subtree
      run: git subtree push --prefix subtree-test "https://omgreenfield:${{ secrets.PUSH_TOKEN }}@github.com/omgreenfield/subtree-test.git" "master"
    - name: Push to subtree2
      run: git subtree push --prefix subtree-test2 "https://omgreenfield:${{ secrets.PUSH_TOKEN }}@github.com/omgreenfield/subtree-test2.git" "master"
