name: Subtree test integration

on:
  push:
    branches: [ master ]

jobs:
  push-subtree-test-changes:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set GitHub config
      run: |
        git config --local user.name "Matthew Greenfield"
        git config --local user.email "mattgreenfield1@gmail.com"
        git config -l | cat
    - name: auth github
      run: |
        mkdir ~/.ssh/
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Push to subtree
      run: git subtree push --prefix subtree-test "https://omgreenfield:cd684ff5df93f02c36a11d9572f53f97b89b95b5@github.com/omgreenfield/subtree-test.git" "master"
    - name: Push to subtree2
      run: git subtree push --prefix subtree-test2 "https://omgreenfield:cd684ff5df93f02c36a11d9572f53f97b89b95b5@github.com/omgreenfield2/subtree-test2.git" "master"
